config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  delete 'delete_all_users', to: "static_pages#delete_all_users"

  devise_for :users, controllers: { 
      omniauth_callbacks: 'users/omniauth_callbacks'
     }
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
        #  :omniauthable

  devise :omniauthable, omniauth_providers: [:google, :facebook, :nhn]

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation! # oauth user email is already confirmed
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def delete_all_users
    User.delete_all
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'All users were successfully deleted.' }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::RegistrationsController
    def google
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        omniauth_user_for_service("google", request)
    end

    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        omniauth_user_for_service("facebook", request)
    end

    def asana
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        omniauth_user_for_service("asana", request)
    end

    def nhn
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        omniauth_user_for_service("nhn", request)
    end

    def failure
        redirect_to root_path
    end


    private 

    def omniauth_user_for_service(service_name, request)
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
            set_flash_message(:notice, :signed_up, kind: service_name.capitalize) if is_navigational_format?
        else
            session["devise.#{service_name.downcase}_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
            set_flash_message(:notice, :failed, kind: service_name.capitalize) if is_navigational_format?
            redirect_to new_user_registration_url
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OauthDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <% unless notice.nil? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>OAuth Demo</h1>
<p>Created with the help of <a href="https://youtu.be/Lut1C6CHDCE?si=w4zNrYeDBBZxyOqs" target="blank">CJ Avilla</a>.</p>
<p>Only a test user can log in with OAuth: joel.esli@gmail.com.
    To add a test user reach out to joel.esli@gmail.com.
</p>
<p>
    A user's email is required to be unique and this prototype does not allow a user
    to authenticate with multiple OAuth providers.
    To test signing in with a different provider you'll need to delete the test user
    if the email for different providers is the same.
</p>
    <%= button_to 'Delete All Users', delete_all_users_path, method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'button is-danger' %>

<p>
    <% if user_signed_in? %>
        <p>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
        </p>
    <% else %>
        <p>
            <%= link_to "Sign in", new_user_session_path(), class: 'button' %>
            <%= link_to "Sign up", new_user_registration_path(), class: 'button' %>
        <p>
    <% end %>
    
</p>